apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitea
  namespace: production
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/gitea-app
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    replicaCount: 1

    ingress:
      host: gitea.local

    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 256Mi

    hpa:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      cpuUtilization: 70